#services:
#  db:
#    image: postgres:16
#    container_name: school-db
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "${PG_PORT}:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  app:
#    build: .
#    container_name: auth-app
#    ports:
#      - "50051:50051"
#    depends_on:
#      - db
#
#volumes:
#  postgres_data:

services:
  db:
    image: postgres:16
    container_name: school-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: